export default [
  { text: "“社恐”如何用英语表达？", link: "/funny/1.md" },
  { text: "“社牛”英语怎么说？", link: "/funny/2.md" },
  { text: "缩写", link: "/funny/3.md" },
  { text: "“惊呆了”英语怎么说？", link: "/funny/4.md" },
  { text: "always 与进行时连用的不同含义", link: "/funny/5.md" },
  { text: "有趣的完全重叠词", link: "/funny/6.md" },
  { text: "短语句型替换", link: "/funny/7.md" },
  { text: "你必须知道的地道表达", link: "/funny/8.md" },
  { text: "用食物来形容一个人", link: "/funny/9.md" },
  { text: "写作中常用的万能短语", link: "/funny/10.md" },
  { text: "常见疑难易错点分析积累", link: "/funny/11.md" },
  { text: "如何用英语称赞别人的能力", link: "/funny/12.md" },
  { text: "香水指南：如何选购一款合适的香水呢？", link: "/funny/13.md" },
  { text: "抢票和唠嗑", link: "/funny/14.md" },
  { text: "安慰", link: "/funny/15.md" },
  { text: "美剧里最常说的俚语", link: "/funny/16.md" },
  { text: "美剧里最常说的俚语", link: "/funny/17.md" },
  { text: "趣味短语", link: "/funny/18.md" },
  { text: "成语", link: "/funny/19.md" },
  { text: "white night", link: "/funny/20.md" },
];
